//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePlayer.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WavePlayer.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BUTTON_TEXT_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_TEXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BUTTON_TEXT_OK {
            get {
                return ResourceManager.GetString("BUTTON_TEXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LABEL_TEXT_COPYRIGHT {
            get {
                return ResourceManager.GetString("LABEL_TEXT_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LABEL_TEXT_LANGUAGE {
            get {
                return ResourceManager.GetString("LABEL_TEXT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Marker position : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LABEL_TEXT_MARKER_POSITION {
            get {
                return ResourceManager.GetString("LABEL_TEXT_MARKER_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing position : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LABEL_TEXT_PLAYING_POSITION {
            get {
                return ResourceManager.GetString("LABEL_TEXT_PLAYING_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LABEL_TEXT_URL {
            get {
                return ResourceManager.GetString("LABEL_TEXT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LABEL_TEXT_VERSION {
            get {
                return ResourceManager.GetString("LABEL_TEXT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LABEL_TEXT_VOLUME {
            get {
                return ResourceManager.GetString("LABEL_TEXT_VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_TEXT_ABOUT {
            get {
                return ResourceManager.GetString("MENU_TEXT_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_TEXT_EXIT {
            get {
                return ResourceManager.GetString("MENU_TEXT_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_TEXT_FILE {
            get {
                return ResourceManager.GetString("MENU_TEXT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_TEXT_OPEN {
            get {
                return ResourceManager.GetString("MENU_TEXT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_TEXT_OPTION {
            get {
                return ResourceManager.GetString("MENU_TEXT_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_TEXT_TOOL {
            get {
                return ResourceManager.GetString("MENU_TEXT_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied current position. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_TEXT_COPIED_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("MESSAGE_TEXT_COPIED_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pasted current position. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_TEXT_PASTED_FROM_CLIPBOARD {
            get {
                return ResourceManager.GetString("MESSAGE_TEXT_PASTED_FROM_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wave files (.wav)|*.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OPEN_FILE_FILTER_WAVE {
            get {
                return ResourceManager.GetString("OPEN_FILE_FILTER_WAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Default language) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECTION_TEXT_LANGUAGE_DEFAULT {
            get {
                return ResourceManager.GetString("SELECTION_TEXT_LANGUAGE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECTION_TEXT_LANGUAGE_ENGLISH {
            get {
                return ResourceManager.GetString("SELECTION_TEXT_LANGUAGE_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECTION_TEXT_LANGUAGE_JAPANESE {
            get {
                return ResourceManager.GetString("SELECTION_TEXT_LANGUAGE_JAPANESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wave file path : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_LABEL_MUSIC_FILE_PATH {
            get {
                return ResourceManager.GetString("STATUS_LABEL_MUSIC_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyzing wave file... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_TEXT_ANALYZING {
            get {
                return ResourceManager.GetString("STATUS_TEXT_ANALYZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while loading or analyzing the wave file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_TEXT_ERROR {
            get {
                return ResourceManager.GetString("STATUS_TEXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading wave file... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_TEXT_LOADING {
            get {
                return ResourceManager.GetString("STATUS_TEXT_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_TEXT_NONE {
            get {
                return ResourceManager.GetString("STATUS_TEXT_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_TEXT_PAUSED {
            get {
                return ResourceManager.GetString("STATUS_TEXT_PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_TEXT_PLAYING {
            get {
                return ResourceManager.GetString("STATUS_TEXT_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready to play. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_TEXT_READY {
            get {
                return ResourceManager.GetString("STATUS_TEXT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WINDOW_TITLE_ABOUT {
            get {
                return ResourceManager.GetString("WINDOW_TITLE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Very Lazy Wave Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WINDOW_TITLE_MAIN {
            get {
                return ResourceManager.GetString("WINDOW_TITLE_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open wave file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WINDOW_TITLE_OPEN {
            get {
                return ResourceManager.GetString("WINDOW_TITLE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WINDOW_TITLE_OPTION {
            get {
                return ResourceManager.GetString("WINDOW_TITLE_OPTION", resourceCulture);
            }
        }
    }
}
